development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: q_and_a_development
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: q_and_a_test
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432